# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-02 15:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('activity_id', models.AutoField(primary_key=True, serialize=False)),
                ('time_begin', models.DateTimeField()),
                ('time_end', models.DateTimeField()),
                ('category', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('time_begin', models.DateTimeField()),
                ('time_end', models.DateTimeField()),
                ('content_raw', models.TextField()),
                ('content_basic_repr', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='log',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workpattern.User'),
        ),
        migrations.AddField(
            model_name='activity',
            name='log_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workpattern.Log'),
        ),
        migrations.AddField(
            model_name='activity',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workpattern.User'),
        ),
    ]
